{% set name = "lume-astra" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9fc3f115419513f3929d1730435b8aaee3d753696abc2dc660732e7ed7812ce9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - distgen
    - numpy
    - openpmd-beamphysics

test:
  imports:
    - astra

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python wrapper for Astra (A Space Charge Tracking Algorithm, DESY) for use in LUME
  description: |
    Tools for analyzing and viewing particle data in the openPMD standard,
    extension beamphysics.

extra:
  recipe-maintainers:
    - ChristopherMayes
